### ISSUE TITLE
Improving markdown using styling

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Psingh12354/Pandas#1]
Hello @Psingh12354,

I just had a walkthrough of your README.md, I would suggest that instead of just using markdown, it would be better if you add 'py' blocks in the markdown syntax, it will add python styling to your pandas codes and also improve the documentation for new comers/beginners who will visit this repo for the first time.

It will make the pandas more readable.

Thank you. Also, please give me a heads up if I could go on to raise a PR on the same.

**Comment by Psingh12354** [comment]
Thank you for your suggestion @ShubhamJagtap2000

**Comment by Psingh12354** [comment]
You can go ahead for PR. I'm always open for improvement.
